/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bandb.cas;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
       // SpringBootApplication classUnderTest = new SpringBootApplication();
     //   assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
