package com.bandb.cas.util.enums;

/**
 * @author buddika on 4/15/19
 * @project bandb-cas
 */
public enum ValidateType {

    EMAIL_NOT_NULL_NOT_EMPTY,
    STRING_NOT_NULL_NOT_EMPTY,
    INT_NOT_ZERO,
    OBJECT_NOT_NULL,
    LINKED_LIST_NOT_NULL_NOT_ZERO_LENGTH,
    PASSWORD_AT_LEAST_ONE_LOWER_CASE,
    PASSWORD_AT_LEAST_ONE_UPPER_CASE,
    PASSWORD_AT_LEAST_ONE_DIGIT,
    PASSWORD_AT_LEAST_ONE_NON_ALPHANUMERIC_CHARACTER,
    PASSWORD_LENGTH_NOT_LESS_THAN_8

}
